server:
  port: 8081
spring:
  datasource:
    name: scm
    url:  jdbc:mysql://localhost:3306/scm
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: scm2.0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL55Dialect 